[package]
name = "fuzzy_controller"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapless = "0.8"
num-traits = { version = "0.2.19", default-features = false, features = ["libm"] }